version: '3'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    volumes:
      - .:/code
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: sqlite_db
    volumes:
      - ./db.sqlite3:/var/lib/sqlite/db.sqlite3
    environment:
      - DJANGO_DB_ENGINE=sqlite3

volumes:
  sqlite_data:
