version: '3'

services:
  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    volumes:
      - .:/code  
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]  
    depends_on:
      - db

  db:
    image: python:3.9
    container_name: sqlite_db
    volumes:
      - .:/code
    environment:
      - DJANGO_DB_ENGINE=sqlite3
